config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'

    resources :projects
    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: %i[index new create] do
      member do
        patch :make_default
      end
    end
  end

  devise_for :users

  root 'projects#index'

  resources :projects, only: %i[index show] do
    resources :tickets do
      collection do
        get :search
      end
      member do
        patch :watch
      end
    end
  end

  scope path: 'tickets/:ticket_id/', as: :ticket do
    resources :comments, only: [:create]
    delete 'tags/:id/remove', to: 'tags#remove', as: :remove_tag
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!

  def index; end

  private

  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: 'You must be an admin to do that.'
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def title(*parts)
    return if parts.empty?

    content_for :title do
      (parts << 'Ticketly').join(' - ')
    end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

app/views/admin/application/index.html.erb
<div class="row">
  <div class="col-md-9">
    <header>
      <h1>Admin Lounge</h1>
    </header>
    <p>Welcome to Ticketly's Admin Lounge. Please enjoy your stay.</p>
  </div>
  <div class="col-md-3">
    <h5 class="text-uppercase mt-4">Admin Links</h5>
    <ul class="nav flex-column">
      <li><%= link_to 'Users', admin_users_path %></li>
      <li><%= link_to 'States', admin_states_path %></li>
      <li><%= link_to 'Projects', admin_projects_path %></li>
    </ul>
  </div>
</div>