config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'

    resources :projects
    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: %i[index new create] do
      member do
        patch :make_default
      end
    end
  end

  devise_for :users

  root 'projects#index'

  resources :projects, only: %i[index show] do
    resources :tickets do
      collection do
        get :search
      end
      member do
        patch :watch
      end
    end
  end

  scope path: 'tickets/:ticket_id/', as: :ticket do
    resources :comments, only: [:create]
    delete 'tags/:id/remove', to: 'tags#remove', as: :remove_tag
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :name, presence: true

  has_many :tickets, dependent: :destroy
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_action :set_project, except: %i[index new create]

  def index
    @projects = Project.all
  end

  def show
    @state = params[:state]&.strip&.titleize

    @tickets = @project.tickets

    return @tickets unless @state

    @tickets = if @state == 'Active'
                 @project.tickets.where.not(state: State.find_by(name: 'Closed'))
               else
                 @project.tickets.where(state: State.find_by(name: @state))
               end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = 'Project has been created.'
      redirect_to @project
    else
      flash.now[:alert] = 'Project has not been created.'
      render 'new'
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      flash[:notice] = 'Project has been updated.'
      redirect_to @project
    else
      flash.now[:alert] = 'Project has not been updated.'
      render 'edit'
    end
  end

  def destroy
    return unless @project.delete

    flash[:notice] = 'Project has been deleted.'
    redirect_to projects_path
  rescue ActiveRecord::InvalidForeignKey
    flash[:alert] = 'Project has tickets and cannot be deleted.'
    redirect_to admin_projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'The project you were looking for could not be found.'
    redirect_to projects_path
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
  end

  def show
    @tickets = @project.tickets
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'The project you were looking for could not be found.'
    redirect_to projects_path
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= bootstrap_form_with(model: [:admin, project], local: true, label_errors: true) do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :description %>
  <%= form.primary %>
<% end %>

app/views/admin/projects/_project.html.erb
<%= link_to project_path(project) do %>
  <tr>
    <td><%= project.id %>
      <td><%= link_to project.name, [project] %>
        <td><%= link_to project.tickets.count, admin_project_path(project) %>
          <td><%= link_to "#{project.tickets.newly_created.count} new", admin_project_path(project, state: 'New') %></td>
          <td><%= link_to "#{project.tickets.closed.count} closed", admin_project_path(project, state: 'Closed') %></td>
          <td><%= link_to "#{project.tickets.active} active", admin_project_path(project, state: 'Active') %></td>
          <td><%= link_to '',
          edit_admin_project_path(project),
          class: "edit" %></td>
          <td><%= link_to 'X',
          admin_project_path(project),
          method: :delete,
          data: { confirm: "Are you sure you want to delete this project?" },
          class: "delete" %></td>
        </tr>
      <% end %>

app/views/admin/projects/edit.html.erb
<header>
  <h1>Edit Project</h1>
</header>

<%= render 'form', project: @project %>

app/views/admin/projects/index.html.erb
<header>
  <h1>Projects</h1>
</header>

<div class="table-responsive">
  <table class="table table-striped table-hover projects">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Tickets</th>
        <th scope="col">New Tickets</th>
        <th scope="col">Closed Tickets</th>
        <th scope="col">Active Tickets</th>
        <th scope="col" colspan="2">Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render @projects %>
    </tbody>
  </table>
</div>

app/views/admin/projects/new.html.erb
<header>
  <h1>New Project</h1>
</header>

<%= render 'form', project: @project %>

app/views/admin/projects/show.html.erb
<header>
  <h1>Project: <%= @project.name %> </h1>
</header>

<header>
  <h3><%= @state %> Tickets</h3>
</header>

<% if @tickets.empty? %>
  No tickets found!
<% else %>
  <div class="table-responsive">
    <table class="table table-striped table-hover tickets">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Comments</th>
          <th scope="col">State</th>
        </tr>
      </thead>
      <tbody>
        <%= render @tickets %>
      </tbody>
    </table>
  </div>
<% end %>