config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'

    resources :projects
    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: %i[index new create] do
      member do
        patch :make_default
      end
    end
  end

  devise_for :users

  root 'projects#index'

  resources :projects, only: %i[index show] do
    resources :tickets do
      collection do
        get :search
      end
      member do
        patch :watch
      end
    end
  end

  scope path: 'tickets/:ticket_id/', as: :ticket do
    resources :comments, only: [:create]
    delete 'tags/:id/remove', to: 'tags#remove', as: :remove_tag
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :name, presence: true

  has_many :tickets, dependent: :destroy
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_action :set_project, except: %i[index new create]

  def index
    @projects = Project.all
  end

  def show
    @state = params[:state]&.strip&.titleize

    @tickets = @project.tickets

    return @tickets unless @state

    @tickets = if @state == 'Active'
                 @project.tickets.where.not(state: State.find_by(name: 'Closed'))
               else
                 @project.tickets.where(state: State.find_by(name: @state))
               end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = 'Project has been created.'
      redirect_to @project
    else
      flash.now[:alert] = 'Project has not been created.'
      render 'new'
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      flash[:notice] = 'Project has been updated.'
      redirect_to @project
    else
      flash.now[:alert] = 'Project has not been updated.'
      render 'edit'
    end
  end

  def destroy
    return unless @project.delete

    flash[:notice] = 'Project has been deleted.'
    redirect_to projects_path
  rescue ActiveRecord::InvalidForeignKey
    flash[:alert] = 'Project has tickets and cannot be deleted.'
    redirect_to admin_projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'The project you were looking for could not be found.'
    redirect_to projects_path
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
  end

  def show
    @tickets = @project.tickets
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'The project you were looking for could not be found.'
    redirect_to projects_path
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/index.html.erb
<header>
  <h1>Projects</h1>
  <% admins_only do %>
    <ul class="actions">
      <li><%= link_to "New Project", new_admin_project_path, class: 'new' %></li>
    </ul>
  <% end %>
</header>
<div class="projects">
  <% @projects.each do |project| %>
    <h2><%= link_to project.name, project %></h2>
    <p><%= project.description %></p>
  <% end %>
</div>

app/views/projects/show.html.erb
<% title @project.name, 'Projects' %>

<header>
  <h1><%= @project.name %></h1>
  <% admins_only do %>
    <ul class="actions">
      <li><%= link_to 'Edit Project', edit_admin_project_path(@project),
        class: 'edit' %></li>
      <li><%= link_to 'Delete Project',
      admin_project_path(@project),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this project?" },
      class: "delete" %></li>
    </ul>
  <% end %>
</header>

<p><%= @project.description %></p>

<header class="page-header">
  <h2>Tickets</h2>
  <ul class="actions">
    <li>
      <%= form_tag search_project_tickets_path(@project), method: :get,
        class: "form-inline" do %>
        <%= label_tag "search", "Search", class: "sr-only" %>
        <%= text_field_tag "search", params[:search], class: "form-control", placeholder: "tag: bug state: open" %>
        <%= submit_tag "Search", class: "btn btn-outline-secondary ml-2" %>
      <% end %>
    </li>
    <li>
      <%= link_to 'New Ticket',
        new_project_ticket_path(@project),
        class: 'new' %>
    </li>
  </ul>
</header>

<ul class="tickets">
  <% @tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> - 
      <%= link_to ticket.name, [@project, ticket] %>
      <%= render ticket.state if ticket.state %>
    </li>
  <% end %>
</ul>