config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'

    resources :projects
    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: %i[index new create] do
      member do
        patch :make_default
      end
    end
  end

  devise_for :users

  root 'projects#index'

  resources :projects, only: %i[index show] do
    resources :tickets do
      collection do
        get :search
      end
      member do
        patch :watch
      end
    end
  end

  scope path: 'tickets/:ticket_id/', as: :ticket do
    resources :comments, only: [:create]
    delete 'tags/:id/remove', to: 'tags#remove', as: :remove_tag
  end
end

app/models/state.rb
class State < ApplicationRecord
  has_many :tickets

  def to_s
    name
  end

  def self.default
    find_by(default: true)
  end

  def make_default!
    State.update_all(default: false)
    update!(default: true)
  end

  scope :search_state, ->(search_term) { where('name LIKE ?', "%#{search_term}%").first }
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::ApplicationController
  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params);
    if @state.save
      flash[:notice] = 'State has been created.'
      redirect_to admin_states_path
    else
      flash.now[:alert] = 'State has not been created.'
      render 'new'
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.make_default!

    flash[:notice] = "'#{@state.name}' is now the default state."
    redirect_to admin_states_path
  end

  private

  def state_params
    params.require(:state).permit(:name, :color)
  end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= bootstrap_form_with(model: [:admin, state], local: true) do |f| %>
  <%= f.text_field :name %>
  <%= f.color_field :color %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/states/index.html.erb
<header>
  <h1>States</h1>

  <ul class="actions">
    <li><%= link_to 'New State', new_admin_state_path, class: 'new' %></li>
  </ul>
</header>

<ul class="states">
  <% @states.each do |state| %>
    <li>
      <%= render 'states/state', state: state %>
      <% if state.default? %>
        (Default)
      <% else %>
        <%= link_to 'Make Default', make_default_admin_state_path(state), method: :patch %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<header>
  <h1>New State</h1>
</header>

<%= render 'form', state: @state %>